name: '🏗️ Build jellyfin-ffmpeg'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - jellyfin
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - jellyfin
    paths-ignore:
      - '**/*.md'

jobs:
##  build_debian:
##    uses: ./.github/workflows/_meta.yaml
##    with:
##      distro: 'debian'
##      codenames: '["buster", "bullseye"]'
##      architectures: '["amd64", "arm64", "armhf"]'
##      release: false

  build_ubuntu:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'ubuntu'
      codenames: '["jammy"]'
      architectures: '["armhf"]'
      release: false

##  build_windows:
##    uses: ./.github/workflows/_meta.yaml
##    with:
##      distro: 'windows'
##      codenames: '["windows"]'
##      architectures: '["win64"]'
##      release: false
